"""Generated-only provisioning. No values, commands, or destinations from argv."""

import fcntl
import hashlib
import json
import os
import re
import secrets
import stat
import uuid


class ProvisionError(Exception):
    pass


def private_json(path):
    fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)
    with os.fdopen(fd) as stream:
        info = os.fstat(stream.fileno())
        if not stat.S_ISREG(info.st_mode) or info.st_mode & 0o077 or info.st_uid != os.getuid() or info.st_size > 65536:
            raise ProvisionError()
        return json.load(stream)


def recipe_for(home, name):
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,63}", name):
        raise ProvisionError()
    recipes = private_json(home / ".config/bws-operations/recipes.json")
    recipe = recipes[name]
    if set(recipe) != {"project_id", "project_name", "secret_name", "fields", "region"}:
        raise ProvisionError()
    if str(uuid.UUID(recipe["project_id"])) != recipe["project_id"]:
        raise ProvisionError()
    if recipe["region"] not in ("us", "eu"):
        raise ProvisionError()
    for key in ("project_name", "secret_name"):
        if not re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9_-]{0,127}", recipe[key]):
            raise ProvisionError()
    fields = recipe["fields"]
    if not isinstance(fields, dict) or not 1 <= len(fields) <= 32:
        raise ProvisionError()
    for key, size in fields.items():
        if not re.fullmatch(r"[A-Z][A-Z0-9_]{0,63}", key) or type(size) is not int or size not in (32, 64):
            raise ProvisionError()
    return recipe


def provision(client, recipe, journal):
    """Caller holds an exclusive journal lock. Journal contains no values."""
    journal.seek(0)
    previous = journal.read()
    binding = recipe
    if previous:
        receipt = json.loads(previous)
        if receipt.get("binding") != binding or receipt.get("status") != "created":
            raise ProvisionError()
        return {"status": "recorded", "secret_id": str(uuid.UUID(receipt["secret_id"]))}

    project = client.projects().get(recipe["project_id"]).data
    if str(project.id) != recipe["project_id"] or project.name != recipe["project_name"]:
        raise ProvisionError()
    org = str(uuid.UUID(str(project.organization_id)))
    # The SDK identifiers endpoint contains keys and IDs, not decrypted values.
    # This is NOT the bws CLI's secret-list operation, which fetches values.
    identifiers = client.secrets().list(org).data.data
    if any(item.key == recipe["secret_name"] for item in identifiers):
        raise ProvisionError()

    def save(receipt):
        journal.seek(0)
        journal.truncate()
        journal.write(json.dumps(receipt))
        journal.flush()
        os.fsync(journal.fileno())

    # Persist uncertainty before the non-idempotent API call. Never blindly
    # retry after a timeout/crash: the remote write might have succeeded.
    save({"status": "pending", "binding": binding})
    value = json.dumps({key: secrets.token_hex(size) for key, size in recipe["fields"].items()})
    result = client.secrets().create(org, recipe["secret_name"], value,
                                     "Generated by approved provisioning recipe", [recipe["project_id"]]).data
    if (result.key != recipe["secret_name"] or result.value != value
            or str(result.organization_id) != org or str(result.project_id) != recipe["project_id"]):
        raise ProvisionError()
    secret_id = str(uuid.UUID(str(result.id)))
    save({"status": "created", "binding": binding, "secret_id": secret_id})
    return {"status": "created", "secret_id": secret_id}


def run(home, name, login):
    recipe = recipe_for(home, name)  # reject before credential access
    state = home / ".local/state/bws-operations"
    state.mkdir(mode=0o700, parents=True, exist_ok=True)
    info = state.lstat()
    if not stat.S_ISDIR(info.st_mode) or info.st_mode & 0o077 or info.st_uid != os.getuid():
        raise ProvisionError()
    target = json.dumps([recipe["region"], recipe["project_id"], recipe["secret_name"]]).encode()
    receipt_name = hashlib.sha256(target).hexdigest() + ".json"
    fd = os.open(state / receipt_name, os.O_RDWR | os.O_CREAT | os.O_NOFOLLOW, 0o600)
    with os.fdopen(fd, "r+") as journal:
        info = os.fstat(journal.fileno())
        if (not stat.S_ISREG(info.st_mode) or info.st_mode & 0o077
                or info.st_uid != os.getuid() or info.st_size > 65536):
            raise ProvisionError()
        fcntl.flock(journal, fcntl.LOCK_EX | fcntl.LOCK_NB)
        directory_fd = os.open(state, os.O_RDONLY | os.O_DIRECTORY | os.O_NOFOLLOW)
        try:
            os.fsync(directory_fd)
        finally:
            os.close(directory_fd)
        return provision(login(recipe["region"]), recipe, journal)
